add support for offset pagination in connections
graphglue/graph-glue pull request #61
Opened 2023-07-03 03:07 UTC by nk-coding

2023-07-03 03:10 UTC, chriku requested changes

2023-07-03 03:10 UTC, chriku commented on graphglue-core/src/main/kotlin/io/github/graphglue/data/execution/NodeQueryExecutor.kt
> +        }
reformat

2023-07-03 18:06 UTC, nk-coding commented on graphglue-core/src/main/kotlin/io/github/graphglue/data/execution/NodeQueryExecutor.kt
> +        }
e61142bb680e73095ea72a3afe746a000ab50b36

2023-07-04 00:15 UTC, chriku approved these changes

2023-07-04 00:30 UTC, merged